name: unifrios_projeto
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  leak_tracker: 10.0.0
  leak_tracker_flutter_testing: 2.0.1
  leak_tracker_testing: 2.0.1
  material_color_utilities: 0.8.0
  meta: 1.11.0
  test_api: 0.6.1
  vm_service: ^13.0.0
  provider: ^6.1.2
  sqflite: ^2.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
  - images/unifrios.png 

uses-material-design: true
